### ISSUE TITLE
Allow do not clear cache

### ISSUE THREAD

**Issue by JoniJnm** [shopsys/phpstorm-inspect#6]
When you clear cache, it is very slow on big projects

**Comment by sustmi** [comment]
Hi @JoniJnm . Thanks for your feedback.

We experienced random PhpStorm false alerts when not clearing the cache.
For example PhpStorm would say that some class does not exist even when it is present. It happens especially if you use one instance of PhpStorm for checking different branches. PhpStorm sometimes cannot invalidate the cache correctly for individual files so we invalidate the whole cache manually.

Did you know about this issue? If you insist we can add a command option to disable cache clearing.

EDIT: I mean something like `--no-cache-clear` option.

**Comment by JoniJnm** [comment]
I tried to clear only the index dir, but as you say, the inspector says that some class does not exists.

So, the clear is needed.
